---

authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: ios
namespace: cisco
description: Ansible Network Collection for Cisco IOS devices.
readme: README.md
repository: https://github.com/ansible-collections/cisco.ios
tags: [cisco, ios, iosxe, networking]
